---
title: "Wer wir sind"
description: |
  Eine Heimat im Theater - Lebendiges Theater, in dem du dich respektiert, geschätzt und zuhause fühlst, für das, was du bist - ganz gleich, wer du bist.
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Das immer wiederkehrende Gefühl des Unwohlseins am Theater hat uns alle irgendwann aus unterschiedlichen Gründen eingeholt.

Ob es daran lag, dass wir einer der wenigen jungen Menschen im Publikum waren oder dass wir am Theater durch Blicke und Taten diskriminiert wurden.

Wir wissen, es geht auch anders, wegen der Freundschaften, die wir bei einer trocken Brezel während den Aufführungspausen, geschlossen haben.

Wir wollen mit euch das Unwohlsein durch Respekt und Heimat ersetzen.

Come as you are.

# WORIN SEHEN WIR UNSERE AUFGABE ALS NTHUSIASTEN?

## Heimat
NTM als Sozialisationsraum mitgestalten 

## Vertretung
Herausforderungen der jungen Stadtgesellschaft im NTM repräsentieren

## Werben
Für bestehende Formate werben